baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'DDAME HTML HUGO'
theme = 'ananke'


[menu]

  [[menu.main]]
  identifier = "accueil"
  name = "Accueil"
  url = "/"
  weight = 1

  [[menu.main]]
  identifier = "a-propos"
  name = "À propos"
  url = "/about/"
  weight = 2

  [[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 3

  [[menu.main]]
  identifier = "post"
  name = "HTML"
  url = "/posts/html"
  weight = 2